# Generated by Django 5.1.6 on 2025-02-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
    ]
